name: ulaskelas
description: Ulaskelas Ristek Universitas Indonesia Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  ristek_material_component: ^0.0.15
  states_rebuilder: ^6.1.0+1
  logger: ^1.0.0
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.4.4
  firebase_core: ^1.10.6
  google_fonts: ^2.2.0
  share: ^2.0.4
  hive: ^1.4.4
  path_provider: ^2.0.8
  rxdart: ^0.27.1
  shared_preferences: ^2.0.11
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  webview_flutter: ^2.8.0
  url_launcher: ^6.0.17
  flutter_switch: ^0.3.2
  universal_html: ^2.0.8
  dio: ^4.0.4
  material_design_icons_flutter: ^4.0.5955
  flutter_vector_icons: ^1.0.0
  package_info: ^2.0.2
  shimmer: ^2.0.0
  envify: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # Help optimization.
  very_good_analysis: ^2.4.0

  #  provides a concrete way of generating files using Dart code.
  build_runner: ^2.2.0

  # See envify.
  envify_generator: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
