name: ulaskelas
description: Ulaskelas Ristek Universitas Indonesia Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  ristek_material_component: ^0.0.15
  states_rebuilder: ^6.1.0+1
  logger: ^2.0.1
  firebase_analytics: ^10.0.0
  firebase_crashlytics: ^3.0.0
  firebase_core: ^2.0.0
  google_fonts: ^4.0.4
  share: ^2.0.4
  hive: ^2.2.3
  path_provider: ^2.0.8
  rxdart: ^0.27.1
  shared_preferences: ^2.0.11
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.17
  flutter_switch: ^0.3.2
  universal_html: ^2.0.8
  dio: ^4.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_vector_icons: ^2.0.0
  package_info: ^2.0.2
  shimmer: ^3.0.0
#  envify: ^2.0.3
  envied: ^0.3.0+3
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # Help optimization.
  very_good_analysis: ^5.0.0+1

  #  provides a concrete way of generating files using Dart code.
  build_runner: ^2.4.6

  # See envify.
#  envify_generator: ^2.0.2
  envied_generator: ^0.3.0+3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
